from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import (
    HomePageView,
    PriorityListView,
    PriorityDeleteView,
    PriorityUpdateView,
    PriorityCreateView,
    CategoryListView,
    CategoryDeleteView,
    CategoryUpdateView,
    CategoryCreateView,
    TaskListView,
    TaskDeleteView,
    TaskUpdateView,
    TaskCreateView,
    NoteListView,
    NoteDeleteView,
    NoteUpdateView,
    NoteCreateView,
    SubTaskListView,
    SubTaskDeleteView,
    SubTaskUpdateView,
    SubTaskCreateView,
)

urlpatterns = [
    path('', HomePageView.as_view(template_name="index.html"), name='home'),
    path('task/', login_required(TaskListView.as_view()), name='task-list'),
    path('priorities/', login_required(PriorityListView.as_view()), name='priority-list'),
    path('priorities/<int:pk>/delete/', login_required(PriorityDeleteView.as_view()), name='priority-delete'),
    path('priorities/<int:pk>/update/', login_required(PriorityUpdateView.as_view()), name='priority-update'),
    path('priorities/create/', login_required(PriorityCreateView.as_view()), name='priority-create'),
    path('categories/', login_required(CategoryListView.as_view()), name='category-list'),
    path('categories/<int:pk>/delete/', login_required(CategoryDeleteView.as_view()), name='category-delete'),
    path('categories/<int:pk>/update/', login_required(CategoryUpdateView.as_view()), name='category-update'),
    path('categories/create/', login_required(CategoryCreateView.as_view()), name='category-create'),
    path('tasks/', login_required(TaskListView.as_view()), name='task-list'),
    path('tasks/<int:pk>/delete/', login_required(TaskDeleteView.as_view()), name='task-delete'),
    path('tasks/<int:pk>/update/', login_required(TaskUpdateView.as_view()), name='task-update'),
    path('tasks/create/', login_required(TaskCreateView.as_view()), name='task-create'),
    path('notes/', login_required(NoteListView.as_view()), name='note-list'),
    path('notes/<int:pk>/delete/', login_required(NoteDeleteView.as_view()), name='note-delete'),
    path('notes/<int:pk>/update/', login_required(NoteUpdateView.as_view()), name='note-update'),
    path('notes/create/', login_required(NoteCreateView.as_view()), name='note-create'),
    path('subtasks/', login_required(SubTaskListView.as_view()), name='subtask-list'),
    path('subtasks/<int:pk>/delete/', login_required(SubTaskDeleteView.as_view()), name='subtask-delete'),
    path('subtasks/<int:pk>/update/', login_required(SubTaskUpdateView.as_view()), name='subtask-update'),
    path('subtasks/create/', login_required(SubTaskCreateView.as_view()), name='subtask-create'),
]
