from django.urls import path
from .views import (
    HomePageView,
    PriorityListView,
    PriorityDeleteView,
    PriorityUpdateView,
    PriorityCreateView,
    CategoryListView,
    CategoryDeleteView,
    CategoryUpdateView,
    CategoryCreateView,
    TaskListView,
    TaskDeleteView,
    TaskUpdateView,
    TaskCreateView,
    NoteListView,
    NoteDeleteView,
    NoteUpdateView,
    NoteCreateView,
    SubTaskListView,
    SubTaskDeleteView,
    SubTaskUpdateView,
    SubTaskCreateView,
)

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('priorities/', PriorityListView.as_view(), name='priority-list'),
    path('priorities/<int:pk>/delete/', PriorityDeleteView.as_view(), name='priority-delete'),
    path('priorities/<int:pk>/update/', PriorityUpdateView.as_view(), name='priority-update'),
    path('priorities/create/', PriorityCreateView.as_view(), name='priority-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/create/', CategoryCreateView.as_view(), name='category-create'),
    path('tasks/', TaskListView.as_view(), name='task-list'),
    path('tasks/<int:pk>/delete/', TaskDeleteView.as_view(), name='task-delete'),
    path('tasks/<int:pk>/update/', TaskUpdateView.as_view(), name='task-update'),
    path('tasks/create/', TaskCreateView.as_view(), name='task-create'),
    path('notes/', NoteListView.as_view(), name='note-list'),
    path('notes/<int:pk>/delete/', NoteDeleteView.as_view(), name='note-delete'),
    path('notes/<int:pk>/update/', NoteUpdateView.as_view(), name='note-update'),
    path('notes/create/', NoteCreateView.as_view(), name='note-create'),
    path('subtasks/', SubTaskListView.as_view(), name='subtask-list'),
    path('subtasks/<int:pk>/delete/', SubTaskDeleteView.as_view(), name='subtask-delete'),
    path('subtasks/<int:pk>/update/', SubTaskUpdateView.as_view(), name='subtask-update'),
    path('subtasks/create/', SubTaskCreateView.as_view(), name='subtask-create'),
]
